import { WalletProvider } from "@/providers";
import "@/styles/globals.css";
import { Inter, Kavoon, Khand } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});
const kavoon = Kavoon({
  subsets: ["latin"],
  variable: "--font-kavoon",
  weight: "400",
});
const khand = Khand({
  subsets: ["latin"],
  variable: "--font-khand",
  weight: "400",
});

export const metadata = {
  title: "Weaveswap",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/assets/svgs/weavelogo.svg" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`font-sans ${inter.variable} ${khand.variable} ${kavoon.variable} w-fit`}
      >
        <WalletProvider>{children}</WalletProvider>
      </body>
    </html>
  );
}
